input:
  table:
    event: signal_lab_events
    batch: signal_lab_event_sets
output:
  collection:
    event: prediction_events
    batch: prediction_event_sets
model:
resolution: 1.0
scheduled_time: "10:30"
