version: "3.7"
services:

  mongo:
    image: mongo:4.0.2
    expose:
    - "27017"
    ports:
    - "27017:27017"
    restart: always
    stop_signal: SIGINT
    # volumes:
    # - ./data/db:/data/db  # durable data
    command: [--noauth, --smallfiles, --quiet]

  jupyter:
    image: quay.io/pennsignals/alpine-3.8-python-3.7-jupyter:v1.0
    depends_on:
    - mongo
    environment:
    - MONGO_URI=mongodb://mongo/notebooks
    expose:
    - "8888"
    ports:
    - "8888:8888"
    volumes:
    - ./:/tmp
    working_dir: /tmp
    entrypoint: [/sbin/tini, --]
    command: [jupyter, lab, --ip=0.0.0.0, --port=8888, --no-browser, --allow-root, --notebook-dir=/tmp]

  microservice:
    build: .
    depends_on:
    - mongo
    environment:
    # - INPUT_URI=mongodb://mongo/tests
    - OUTPUT_URI=mongodb://mongo/tests
    working_dir: /tmp
    entrypoint: ["microservice.run_once_now"]  # see setup.py console_scripts
