version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build application image
          command: docker build -t pennsignals/microservice:$CIRCLE_BUILD_NUM .
          no_output_timeout: 1200
      - run:
          name: run tests in setup.py
          command: docker run -it --rm pennsignals/microservice:$CIRCLE_BUILD_NUM  /bin/ash -c 'COVERAGE_STORAGE=json python setup.py test'
          no_output_timeout: 1200
      - run:
          name: push to quay.io after tests pass
          command: |
            docker login quay.io -u $QUAY_USER -p $QUAY_PASS
            docker push quay.io/pennsignals/microservice:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-test-push:
    jobs:
      - build:
          context: Quay.io

