version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build application image
          command: 'docker build -t pennsignals/app-image .'
          no_output_timeout: 1200
      - run:
          name: Test
          command: docker run -it --rm pennsignals/app-image  /bin/ash -c 'COVERAGE_STORAGE=json python setup.py test'
          no_output_timeout: 1200
