version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build application image
          command: 'docker build -t pennsignals/app-image .'
          no_output_timeout: 1200
  test:
    docker:
      - image: pennsignals/app-image
    steps:
      - checkout
      - run:
          name: Test
          command: 'python setup.py test'
          no_output_timeout: 1200

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
